# Generated by Django 4.2.1 on 2023-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='passage',
        ),
        migrations.AddField(
            model_name='photo',
            name='passage',
            field=models.ManyToManyField(to='points.passage'),
        ),
    ]
