# Generated by Django 4.2.1 on 2023-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_passage_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='connect',
            field=models.TextField(default=' '),
        ),
    ]
